-- Consulta com JOIN — tarefa "Dados & Consulta SQL" (Integrante 2, Etapa 1).
-- Passo a passo completo: cartões [E1] da sua lista no Trello.
--
-- O que este arquivo precisa ter:
--   Uma única consulta que devolve uma linha por pagamento, já com os dados
--   do imóvel e do tipo, usando INNER JOIN entre as 3 tabelas.
--
-- As colunas do resultado, nomeadas com AS exatamente assim:
--   id_venda, data_do_pagamento, valor_do_pagamento,
--   codigo_imovel, descricao_imovel, tipo_imovel
--
-- Esta é a consulta que o backend inteiro reaproveita na Etapa 2.
