-- Massa de dados — tarefa "Banco de dados" (Integrante 1, Etapa 1).
-- Passo a passo completo: cartões [E1] da sua lista no Trello.
--
-- O que este arquivo precisa ter:
--   1. INSERT dos tipos de imóvel
--   2. INSERT de no mínimo 8 imóveis, de tipos variados
--   3. INSERT de no mínimo 30 pagamentos, cobrindo no mínimo 5 meses distintos
--
-- Todo imóvel precisa ter pelo menos 1 pagamento.
-- A ordem importa: tipo_imovel, depois imovel, depois pagamento.
